### ISSUE TITLE
Potential issue with php 7.4 typed

### ISSUE THREAD

**Issue by SonyPradana** [SonyPradana/php-mvc#15]
container [mixed type](https://github.com/SonyPradana/php-library/pull/316) adding alias, with calling get has make, where it required return mixed. return mixed available in php 8.

**Comment by anggerpradana** [comment]
somehow php-library test in 7.4 still work. i will test in local 🧐.

**Comment by SonyPradana** [comment]
bc already

**Comment by SonyPradana** [comment]
bc already 🥺
